-- Add USDZ companion and half-body variant columns to avatars table.
--
-- usdz_key: R2 storage key for the iOS Quick Look USDZ counterpart of the
-- avatar GLB. Generated client-side at upload time via Three.js
-- USDZExporter. Lets iOS Safari open the avatar in AR without a USDZ URL
-- being supplied externally.
--
-- halfbody_key: R2 storage key for the optional half-body (waist-up) GLB
-- variant used in VR / first-person contexts. Generated by stripping the
-- lower-body bone hierarchy and mesh from the source avatar.

ALTER TABLE avatars
	ADD COLUMN IF NOT EXISTS usdz_key text,
	ADD COLUMN IF NOT EXISTS halfbody_key text;

CREATE INDEX IF NOT EXISTS idx_avatars_usdz_key
	ON avatars (usdz_key)
	WHERE usdz_key IS NOT NULL;
