import {
  feActivity, feBarChart, feBell, feBookOpen, feCheckSquare,
  feClock, feCode, feCpu, feEdit2, feGlobe, feGrid,
  feImage, feInbox, feLayers, feLayout, feList, feMail,
  feMonitor, fePenTool, fePlayCircle, feSearch, feSliders,
  feSmartphone, feTarget, feUpload, feUsers, feZap,
} from '../../feather.js';

export const featurePages = {
  'web-app': {
    eyebrow: 'AI Web App',
    title: 'Build full-stack apps from a single prompt',
    sub: 'Manus generates the frontend, backend, database, and deploys it — no engineering team required.',
    primaryCta: 'Start building',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Real frameworks',        body: 'Next.js, Postgres, Auth, Stripe — production-grade defaults.',                    icon: feCode },
      { title: 'One-click deploys',      body: 'Push to your own domain, with HTTPS and previews per branch.',                    icon: feUpload },
      { title: 'Editable from chat',     body: 'Iterate on copy, layout, and logic without leaving the conversation.',             icon: feEdit2 },
      { title: 'Built-in observability', body: 'Errors, traces, and costs visible from the start.',                               icon: feActivity },
      { title: 'Bring your stack',       body: 'Swap any default — your DB, your auth, your CDN.',                                icon: feGrid },
      { title: 'Team review',            body: 'Comment on diffs, approve before deploy.',                                        icon: feUsers },
    ],
    closingTitle: 'Ship a real app today.',
    closingCta: 'Start free',
  },

  'mobile-app': {
    eyebrow: 'AI Mobile App',
    title: 'Native iOS & Android apps, generated end-to-end',
    sub: 'From idea to App Store — Manus writes the code, wires the APIs, and handles the release build.',
    primaryCta: 'Build your app',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Cross-platform code',    body: 'React Native or Flutter — idiomatic output, not scaffolded boilerplate.',          icon: feSmartphone },
      { title: 'App Store submission',   body: 'Signed builds, metadata, and screenshots ready to submit.',                       icon: feUpload },
      { title: 'Push & deep links',      body: 'APNs, FCM, and universal links configured from the first run.',                   icon: feBell },
      { title: 'Live preview',           body: 'See your app on a real device before pushing to production.',                     icon: feMonitor },
      { title: 'Auth & payments',        body: 'Apple Sign-In, Google OAuth, and Stripe ready from day one.',                     icon: feCheckSquare },
      { title: 'Team CI/CD',             body: 'Every merge triggers a fresh build — no manual release steps.',                   icon: feUsers },
    ],
    closingTitle: 'Launch your app this week.',
    closingCta: 'Start free',
  },

  'ai-design': {
    eyebrow: 'AI Design',
    title: 'From brief to brand: design that ships itself',
    sub: 'Describe your product, brand, or screen — Manus delivers complete, export-ready design files.',
    primaryCta: 'Start designing',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Brand systems',          body: 'Logos, color palettes, and type scales generated as a coherent whole.',            icon: fePenTool },
      { title: 'Figma-ready exports',    body: 'Components, variables, and styles structured for handoff.',                       icon: feImage },
      { title: 'Responsive layouts',     body: 'Desktop, tablet, and mobile frames produced in a single pass.',                   icon: feLayout },
      { title: 'Iterate in chat',        body: 'Adjust tone, color, or density with plain-language instructions.',                icon: feEdit2 },
      { title: 'Asset library',          body: 'Icons, illustrations, and photography matched to your brand style.',              icon: feGrid },
      { title: 'Review & approve',       body: 'Share a preview link with stakeholders before any handoff.',                      icon: feCheckSquare },
    ],
    closingTitle: 'Design your brand in an afternoon.',
    closingCta: 'Start designing',
  },

  'ai-slides': {
    eyebrow: 'AI Slides',
    title: 'Decks that write, design, and rehearse with you',
    sub: 'Tell Manus your audience and key message. Get a polished, presentation-ready deck in minutes.',
    primaryCta: 'Create a deck',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Smart outlines',         body: 'Manus structures your narrative before designing a single slide.',                 icon: feList },
      { title: 'On-brand layouts',       body: 'Themes that match your palette, fonts, and grid — automatically.',                icon: feLayout },
      { title: 'Speaker notes',          body: 'Every slide ships with talking points and transition cues.',                      icon: feEdit2 },
      { title: 'Live data charts',       body: 'Pull in your numbers; Manus picks the right chart type automatically.',           icon: feBarChart },
      { title: 'Rehearsal mode',         body: 'Practice your timing with auto-advance and an inline teleprompter.',              icon: fePlayCircle },
      { title: 'Share & export',         body: 'PowerPoint, PDF, or a shareable link — one click away.',                         icon: feUpload },
    ],
    closingTitle: 'Present with confidence.',
    closingCta: 'Create your deck',
  },

  'browser-operator': {
    eyebrow: 'Browser Operator',
    title: 'Lend Manus a tab. Watch it work.',
    sub: 'Give Manus access to a browser tab and it completes multi-step web tasks while you focus on other things.',
    primaryCta: 'Try it now',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Full page control',      body: 'Clicks, scrolls, form fills, and file uploads — no task too complex.',            icon: feMonitor },
      { title: 'Multi-tab flows',        body: 'Research across sites, compare prices, and aggregate results in one pass.',       icon: feGlobe },
      { title: 'Authenticated sessions', body: 'Manus works inside your logged-in accounts, safely sandboxed.',                   icon: feCheckSquare },
      { title: 'Parallel browsing',      body: 'Spin up multiple agents to run independent web tasks concurrently.',              icon: feGrid },
      { title: 'Audit trail',            body: 'Every action logged — see exactly what was clicked and when.',                    icon: feActivity },
      { title: 'Scheduled runs',         body: 'Set Manus to monitor a site or submit a form on a recurring schedule.',          icon: feClock },
    ],
    closingTitle: 'Never click through a workflow again.',
    closingCta: 'Try it free',
  },

  'wide-research': {
    eyebrow: 'Wide Research',
    title: 'Parallel research across hundreds of sources at once',
    sub: 'Manus dispatches a fleet of agents to explore the web, synthesising findings into a single citable report.',
    primaryCta: 'Start researching',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Hundreds of sources',    body: 'Academic papers, news, forums, and market data — searched simultaneously.',       icon: feSearch },
      { title: 'Cited outputs',          body: 'Every claim linked to its source — no hallucinated references.',                  icon: feBookOpen },
      { title: 'Configurable depth',     body: 'Set breadth vs. depth for quick briefs or exhaustive deep-dives.',               icon: feSliders },
      { title: 'Structured exports',     body: 'Markdown, PDF, or structured JSON ready for downstream use.',                    icon: feList },
      { title: 'Competitive intel',      body: 'Track rivals, pricing, and sentiment across the web automatically.',             icon: feTarget },
      { title: 'Scheduled sweeps',       body: 'Run the same query weekly and get a concise diff of what changed.',              icon: feClock },
    ],
    closingTitle: 'Get better research done faster.',
    closingCta: 'Start free',
  },

  'mail-manus': {
    eyebrow: 'Mail Manus',
    title: 'Turn every inbox thread into a finished task',
    sub: 'Connect your inbox and Manus drafts replies, schedules actions, and closes loops — without you lifting a finger.',
    primaryCta: 'Connect your inbox',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Smart triage',           body: 'Manus reads context, urgency, and intent — not just keywords.',                   icon: feInbox },
      { title: 'Draft in your voice',    body: 'Replies that sound like you, tuned to your past writing patterns.',              icon: feEdit2 },
      { title: 'Action extraction',      body: 'Meeting requests, to-dos, and follow-ups turned into calendar items.',           icon: feCheckSquare },
      { title: 'Thread summaries',       body: 'Long threads distilled into a three-line brief before you reply.',               icon: feList },
      { title: 'Rules & routing',        body: 'Custom logic to forward, label, or delegate automatically.',                     icon: feSliders },
      { title: 'Team shared inbox',      body: 'Assign, co-draft, and track accountability across your whole team.',             icon: feUsers },
    ],
    closingTitle: 'Reach inbox zero. Stay there.',
    closingCta: 'Connect your inbox',
  },

  'agent-skills': {
    eyebrow: 'Agent Skills',
    title: 'Codify your team\'s expertise into reusable agents',
    sub: 'Record a workflow once and Manus runs it reliably at any scale — no maintenance, no documentation drift.',
    primaryCta: 'Build a skill',
    secondaryCta: 'Watch a 2-min demo',
    features: [
      { title: 'Skill recorder',         body: 'Walk through a task once; Manus captures the pattern as a reusable skill.',      icon: feCpu },
      { title: 'Parameterised runs',     body: 'Swap inputs to reuse the same skill across clients, markets, or datasets.',      icon: feSliders },
      { title: 'Team library',           body: 'Share, fork, and version skills across your entire organisation.',               icon: feUsers },
      { title: 'Composable chains',      body: 'Sequence skills into multi-step pipelines with conditional branching.',          icon: feLayers },
      { title: 'Reliability monitoring', body: 'Track success rate, drift, and latency for every skill run.',                    icon: feActivity },
      { title: 'Access controls',        body: 'Scope skills to roles, departments, or individual contributors.',                icon: feTarget },
    ],
    closingTitle: 'Turn expertise into infrastructure.',
    closingCta: 'Build your first skill',
  },
};
