// This is a placeholder IDL. In a real environment, this file would be
// generated by running `anchor build` in the `contracts/agent-invocation` directory.

export type AgentInvocation = {
  "version": "0.1.0",
  "name": "agent_invocation",
  "instructions": [
    {
      "name": "invokeSkill",
      "accounts": [
        {
          "name": "invokerAgent",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "targetAgent",
          "isMut": false,
          "isSigner": false
        },
        {
          "name": "invokerAuthority",
          "isMut": true,
          "isSigner": true
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "skillName",
          "type": "string"
        },
        {
          "name": "parameters",
          "type": "string"
        }
      ]
    }
  ]
};

export const IDL: AgentInvocation = {
  "version": "0.1.0",
  "name": "agent_invocation",
  "instructions": [
    {
      "name": "invokeSkill",
      "accounts": [
        {
          "name": "invokerAgent",
          "isMut": false,
          "isSigner": false,
          "docs": ["CHECK: This is the agent performing the invocation"]
        },
        {
          "name": "targetAgent",
          "isMut": false,
          "isSigner": false,
          "docs": ["CHECK: This is the agent whose skill is being invoked"]
        },
        {
          "name": "invokerAuthority",
          "isMut": true,
          "isSigner": true,
          "docs": ["CHECK: The user or authority wallet for the invoker"]
        },
        {
          "name": "systemProgram",
          "isMut": false,
          "isSigner": false
        }
      ],
      "args": [
        {
          "name": "skillName",
          "type": "string"
        },
        {
          "name": "parameters",
          "type": "string"
        }
      ]
    }
  ]
};
