// The tool policy: every tool on every three.ws MCP server, with its group,
// tier, and, for a financial tool, the confirm flag it requires and the preview
// tool that must run first.
//
// This table is the single source of truth. Hosted servers and stdio packages
// read it at runtime, scripts/build-mcp-skill.mjs renders the model-facing
// skill document from it, and tests/mcp-policy.test.js fails when a server
// ships a tool this table does not classify.
//
// Row helpers:
//   r(group)                         read tier
//   w(group)                         write tier
//   f(group, flag, preview, bind)    financial tier. `bind` lists arguments that
//                                    must match between the preview and the
//                                    call; 'handle>to' means the preview's
//                                    `handle` must equal the call's `to`.
//   own(group, flag, preview)        financial tier whose tool verifies its own
//                                    preview id (the policy layer enforces the
//                                    enablement and the confirm flag only).

const r = (group) => ({ group, tier: 'read' });
const w = (group) => ({ group, tier: 'write' });
const f = (group, confirmFlag, previewTool, bind = []) => ({ group, tier: 'financial', confirmFlag, previewTool, bind });
const own = (group, confirmFlag, previewTool) => ({ group, tier: 'financial', confirmFlag, previewTool, ownsPreview: true });

// Tools a hosted server shares through a common module, listed once.
const GETTING_STARTED = { getting_started: r('utility') };
const READ_RESOURCE = { read_resource: r('utility') };
const MODEL_TOOLS = {
	inspect_model: r('assets'),
	optimize_model: r('assets'),
	validate_model: r('assets'),
	list_animations: r('assets'),
	animation_signature: r('assets'),
	find_similar_animations: r('assets'),
	apply_animation: w('assets'),
	text_to_animation: w('assets'),
};
const PUMP_MARKET = {
	search_tokens: r('intelligence'),
	get_token_details: r('intelligence'),
	get_bonding_curve: r('intelligence'),
	get_token_trades: r('intelligence'),
	get_trending_tokens: r('intelligence'),
	get_new_tokens: r('intelligence'),
	get_graduated_tokens: r('intelligence'),
	get_king_of_the_hill: r('intelligence'),
	get_creator_profile: r('intelligence'),
	get_token_holders: r('intelligence'),
	kol_leaderboard: r('intelligence'),
	pumpfun_bot_status: r('utility'),
	pumpfun_first_claims: r('intelligence'),
	pumpfun_list_claims: r('intelligence'),
	pumpfun_watch_claims: r('intelligence'),
	pumpfun_watch_whales: r('intelligence'),
	pumpfun_quote_swap: r('trading'),
	pumpfun_vanity_mint: r('launch'),
	sns_resolve: r('utility'),
	social_cashtag_sentiment: r('intelligence'),
	social_x_post_impact: r('intelligence'),
};

export const POLICY = {
	// ── Hosted servers ────────────────────────────────────────────────────────

	// /api/mcp
	'three.ws': {
		...GETTING_STARTED,
		...READ_RESOURCE,
		...MODEL_TOOLS,
		attach_avatar_to_agent: w('agents'),
		call_agent: w('agents'),
		copy_status: r('trading'),
		copy_subscribe: w('trading'),
		create_agent: w('agents'),
		create_gated_embed: w('integrations'),
		crypto_data: r('intelligence'),
		delete_avatar: f('assets', 'confirm_delete', 'get_avatar', ['id']),
		diff_models: r('assets'),
		forget: f('agents', 'confirm_delete', 'recall', ['agent_id']),
		garment_status: r('assets'),
		generate_garment: w('assets'),
		get_3d_asset_onchain: r('assets'),
		get_avatar: r('assets'),
		get_catalog_item: r('assets'),
		get_embed_code: r('integrations'),
		get_feedback_repro: r('utility'),
		get_item_source: r('assets'),
		identity_check: r('agents'),
		list_feedback: r('utility'),
		list_garment_catalog: r('assets'),
		list_my_avatars: r('assets'),
		list_sign_vocabulary: r('assets'),
		mint_3d_asset: w('assets'),
		oracle_arm_watch: f('trading', 'confirm_spend', 'oracle_watch_status', ['agent_id']),
		oracle_coin: r('intelligence'),
		oracle_top_plays: r('intelligence'),
		oracle_watch_status: r('intelligence'),
		print_analyze: r('assets'),
		print_quote: r('assets'),
		pumpfun_creator_intel: r('intelligence'),
		pumpfun_recent_claims: r('intelligence'),
		pumpfun_recent_graduations: r('intelligence'),
		pumpfun_token_intel: r('intelligence'),
		recall: r('agents'),
		register_agent: w('agents'),
		remember: w('agents'),
		render_avatar: r('assets'),
		render_avatar_image: w('assets'),
		search_catalog: r('assets'),
		search_public_avatars: r('assets'),
		sign_text: r('assets'),
		solana_agent_attestations: r('agents'),
		solana_agent_passport: r('agents'),
		solana_agent_reputation: r('agents'),
		token_snapshot: r('intelligence'),
		trader_leaderboard: r('intelligence'),
		trader_profile: r('intelligence'),
		home_status: r('integrations'),
		home_list_macros: r('integrations'),
		home_grants: r('integrations'),
		home_activate: f('integrations', 'confirm_run', 'home_list_macros', ['home_id']),
		home_call: f('integrations', 'confirm_run', 'home_status', ['home_id']),
		list_available_skills: r('skills'),
		import_community_skill: w('skills'),
		list_custom_skills: r('skills'),
		get_custom_skill: r('skills'),
		create_custom_skill: w('skills'),
		update_custom_skill: w('skills'),
		delete_custom_skill: f('skills', 'confirm_delete', 'get_custom_skill', ['agent_id', 'skill_id']),
	},

	// /api/mcp-agent
	'threews-agent': {
		...GETTING_STARTED,
		...READ_RESOURCE,
		wallet_status: r('wallet'),
		provision_wallet: w('wallet'),
		find_services: r('x402'),
		pay_quote: r('x402'),
		pay_and_call: f('x402', 'confirm_payment', 'pay_quote', ['resource_url']),
		monetize_endpoint: w('x402'),
		swap_quote: r('trading'),
		swap_execute: f('trading', 'confirm_swap', 'swap_quote'),
		browse_marketplace: r('marketplace'),
		browse_public_agents: r('marketplace'),
		get_listing: r('marketplace'),
		get_marketplace_history: r('marketplace'),
		preview_marketplace_action: r('marketplace'),
		create_marketplace_listing: own('marketplace', 'confirm_listing', 'preview_marketplace_action'),
		delist_marketplace_listing: own('marketplace', 'confirm_delist', 'preview_marketplace_action'),
		place_bid: own('marketplace', 'confirm_bid', 'preview_marketplace_action'),
		buy_now: own('marketplace', 'confirm_payment', 'preview_marketplace_action'),
		get_my_bids: r('marketplace'),
		get_received_bids: r('marketplace'),
		accept_marketplace_bid: own('marketplace', 'confirm_accept', 'preview_marketplace_action'),
		reject_marketplace_bid: w('marketplace'),
		withdraw_marketplace_bid: own('marketplace', 'confirm_withdraw', 'preview_marketplace_action'),
		get_agent_transfer: r('marketplace'),
		resume_agent_transfer: w('marketplace'),
	},

	// /api/mcp-3d
	'threews-3d-studio': {
		...GETTING_STARTED,
		...READ_RESOURCE,
		...MODEL_TOOLS,
		text_to_3d: w('assets'),
		image_to_3d: w('assets'),
		generation_status: r('assets'),
		capture_scene: w('assets'),
		preview_3d: r('assets'),
		remove_background: w('assets'),
		remesh_model: w('assets'),
		stylize_model: w('assets'),
		segment_model: w('assets'),
		retexture_model: w('assets'),
		retexture_region: w('assets'),
		auto_rig_model: w('assets'),
		pose_model: r('assets'),
		direct_prompt: w('assets'),
		generate_material: w('assets'),
		save_avatar: w('assets'),
		export_ar: r('assets'),
		verify_provenance: r('assets'),
		anchor_provenance: w('assets'),
		grade_sim_readiness: r('assets'),
		validate_spatial_response: r('utility'),
		create_agent_persona: w('agents'),
		get_agent_persona: r('agents'),
		persona_say: w('agents'),
		persona_identity: r('wallet'),
		persona_payment_preview: r('wallet'),
		persona_tip: f('wallet', 'confirm_send', 'persona_payment_preview', ['persona_id', 'to', 'usdc']),
		persona_send: f('wallet', 'confirm_send', 'persona_payment_preview', ['persona_id', 'to', 'usdc']),
		x402_preflight: r('x402'),
	},

	// /api/mcp-studio (free, keyless)
	'threews-3d-studio-free': {
		forge_free: w('assets'),
		text_to_avatar: w('assets'),
		mesh_forge: w('assets'),
		rig_mesh: w('assets'),
		forge_avatar: w('assets'),
		refine_model: w('assets'),
		check_job: w('assets'),
		look_at_model: r('assets'),
		create_agent_persona: w('agents'),
		get_agent_persona: r('agents'),
		persona_say: w('agents'),
	},

	// /api/mcp-bazaar
	'threews-x402-bazaar': {
		...GETTING_STARTED,
		...READ_RESOURCE,
		search_services: r('x402'),
		browse_services: r('x402'),
		get_service: r('x402'),
		bazaar_service_details: r('x402'),
	},

	// /api/ibm-mcp
	'ibm-x402-mcp-remote': {
		...GETTING_STARTED,
		ibm_granite_getting_started: r('utility'),
		ibm_granite_chat: r('chat'),
		ibm_granite_code: r('chat'),
		ibm_granite_embed: r('chat'),
		ibm_granite_analyze: r('chat'),
		ibm_granite_forecast: r('chat'),
	},

	// /api/pump-fun-mcp
	'threews-pumpfun': {
		...PUMP_MARKET,
		sns_reverseLookup: r('utility'),
		get_coin_intel: r('intelligence'),
		get_oracle_conviction: r('intelligence'),
		pumpfun_upload_metadata: w('launch'),
	},

	// ── stdio packages (npx -y @three-ws/<name>) ──────────────────────────────

	'activity-mcp': {
		get_feed_events: r('intelligence'),
		get_holder_leaderboard: r('intelligence'),
		get_tier_info: r('intelligence'),
		get_trending_agents: r('intelligence'),
		get_trending_coins: r('intelligence'),
	},
	'agenc-mcp': {
		get_agent: r('agents'),
		get_task: r('marketplace'),
		link_agent: r('agents'),
		list_tasks: r('marketplace'),
		query_x402_services: r('x402'),
	},
	'agentcore-payments-mcp': {
		create_payment_session: w('x402'),
		quote_session_payment: r('x402'),
		pay_with_session: f('x402', 'confirm_payment', 'quote_session_payment', ['url', 'method']),
		check_payment_session: r('x402'),
		list_payment_sessions: r('x402'),
		cancel_payment_session: f('x402', 'confirm_delete', 'check_payment_session', ['session_id']),
	},
	'agora-mcp': {
		agora_board: r('marketplace'),
		agora_pulse: r('marketplace'),
		agora_citizens: r('marketplace'),
		agora_passport: r('marketplace'),
		agora_professions: r('marketplace'),
		agora_quote_register: r('marketplace'),
		agora_register: f('marketplace', 'confirm_spend', 'agora_quote_register', ['handle', 'erc8004AgentId', 'mplCoreAsset', 'stakeLamports', 'cluster']),
		agora_claim_task: w('marketplace'),
		agora_complete_task: w('marketplace'),
		agora_quote_task: r('marketplace'),
		agora_post_task: f('marketplace', 'confirm_spend', 'agora_quote_task', ['description', 'rewardAmount', 'rewardMint', 'maxWorkers', 'cluster']),
	},
	'alerts-mcp': {
		create_alert_rule: w('intelligence'),
		update_alert_rule: w('intelligence'),
		delete_alert_rule: f('intelligence', 'confirm_delete', 'list_alert_rules'),
		get_alert_history: r('intelligence'),
		list_alert_rules: r('intelligence'),
	},
	'alibaba-cloud-mcp': {
		qwen_chat: r('chat'),
		qwen_embed: r('chat'),
		qwen_list_models: r('chat'),
	},
	'assistant-mcp': {
		build_assistant_widget: r('integrations'),
		list_assistant_options: r('integrations'),
	},
	'audio-mcp': {
		audio_to_face: r('assets'),
		motion_capture_clip: r('assets'),
		motion_capture_clips: r('assets'),
		speech_to_text: r('utility'),
		text_to_speech: r('utility'),
	},
	'autopilot-mcp': {
		adjust_proposal: w('runs'),
		compute_trust: r('runs'),
		dismiss_proposal: w('runs'),
		dryrun_proposal: r('runs'),
		execute_proposal: f('runs', 'confirm_transfer', 'dryrun_proposal', ['agentId', 'proposalId']),
		generate_proposals: w('runs'),
		get_autopilot_config: r('runs'),
		list_autopilot_activity: r('runs'),
		list_proposals: r('runs'),
		set_autopilot_config: w('runs'),
		undo_action: w('runs'),
	},
	'avatar-agent-mcp': {
		inspect_glb: r('assets'),
		validate_glb: r('assets'),
		optimize_glb: r('assets'),
		thumbnail_glb: r('assets'),
		viewer_url: r('assets'),
		list_avatars: r('assets'),
		list_animations: r('assets'),
		spawn_avatar: w('assets'),
		dress_avatar: w('assets'),
		render_avatar: r('assets'),
		generate_avatar: w('assets'),
		speak: w('assets'),
		wallet_create: w('wallet'),
		wallet_balance: r('wallet'),
		wallet_send_preview: r('wallet'),
		wallet_send: f('wallet', 'confirm_transfer', 'wallet_send_preview', ['to', 'sol']),
		pump_snapshot: r('intelligence'),
		pump_buy_quote: r('trading'),
		pump_buy: f('trading', 'confirm_swap', 'pump_buy_quote', ['target', 'buySol', 'slippageBps', 'jitoBundle']),
		pump_launch_preview: r('launch'),
		pump_launch: f('launch', 'confirm_launch', 'pump_launch_preview', ['name', 'symbol', 'rentSol', 'devBuySol', 'jitoTipSol']),
		pump_collect_preview: r('launch'),
		pump_collect_fees: f('launch', 'confirm_withdraw', 'pump_collect_preview', ['destination']),
		ens_sns_resolve: r('utility'),
	},
	'billing-mcp': {
		export_billing_history: r('billing'),
		get_billing_summary: r('billing'),
		get_fee_info: r('billing'),
		get_receipt: r('billing'),
		query_usage: r('billing'),
	},
	'blender-mcp': {
		blender_convert: w('assets'),
		blender_forge_import: w('assets'),
		blender_info: r('assets'),
		blender_optimize: w('assets'),
		blender_render: w('assets'),
		blender_run_python: f('assets', 'confirm_run', 'blender_info'),
		blender_scene_info: r('assets'),
	},
	'brain-mcp': {
		chat: r('chat'),
		list_providers: r('chat'),
	},
	'clash-mcp': {
		enlist_faction: w('utility'),
		get_clash_leaderboard: r('utility'),
		get_clash_state: r('utility'),
		rally_faction: w('utility'),
	},
	'concierge-mcp': {
		concierge_ask: r('integrations'),
		concierge_avatars: r('integrations'),
		concierge_embed: r('integrations'),
	},
	'copy-mcp': {
		cancel_subscription: f('trading', 'confirm_delete', 'list_subscriptions'),
		create_subscription: w('trading'),
		get_earnings: r('trading'),
		get_executions: r('trading'),
		list_subscriptions: r('trading'),
		record_execution: w('trading'),
		update_subscription: w('trading'),
	},
	'herald-mcp': {
		announce: w('mail'),
		announce_result: w('mail'),
		check_rail: r('mail'),
	},
	'home-mcp': {
		home_overview: r('integrations'),
		list_entities: r('integrations'),
		list_macros: r('integrations'),
		call_service: f('integrations', 'confirm_run', 'list_entities'),
		preview_macro: r('integrations'),
		run_macro: f('integrations', 'confirm_run', 'preview_macro', ['phrase']),
	},
	'ibm-watsonx-mcp': {
		watsonx_chat: r('chat'),
		watsonx_embed: r('chat'),
		watsonx_forecast: r('chat'),
		watsonx_generate: r('chat'),
		watsonx_list_models: r('chat'),
		watsonx_tokenize: r('chat'),
	},
	'ibm-x402-mcp': {
		ibm_granite_getting_started: r('utility'),
		ibm_granite_chat: r('chat'),
		ibm_granite_code: r('chat'),
		ibm_granite_embed: r('chat'),
		ibm_granite_analyze: r('chat'),
		ibm_granite_forecast: r('chat'),
	},
	'intel-mcp': {
		copy_smart_wallets: r('intelligence'),
		kol_leaderboard: r('intelligence'),
		kol_trades: r('intelligence'),
		signal_feed: r('intelligence'),
		smart_money_coin: r('intelligence'),
		wallet_intel: r('intelligence'),
	},
	'knock-mcp': {
		knock_act: w('mail'),
		knock_directory: r('mail'),
		knock_inbox: r('mail'),
		knock_quote: r('mail'),
		knock_receipt: r('mail'),
		knock_send: w('mail'),
	},
	'kol-mcp': {
		get_wallet_portfolio: r('intelligence'),
		get_wallet_trades: r('intelligence'),
	},
	'loom-mcp': {
		get_creation: r('assets'),
		get_loom_feed: r('assets'),
		submit_creation: w('assets'),
	},
	'marketplace-mcp': {
		agent_categories: r('marketplace'),
		agent_detail: r('marketplace'),
		browse_agents: r('marketplace'),
		browse_skills: r('marketplace'),
		skill_categories: r('marketplace'),
	},
	'metaplex-agent-mcp': {
		preview_agent_mint: r('agents'),
		mint_onchain_agent: f('agents', 'confirm_spend', 'preview_agent_mint', ['network', 'name']),
		prepare_agent_mint: r('agents'),
		send_signed_transaction: f('agents', 'confirm_send', 'prepare_agent_mint'),
		preview_agent_identity: r('agents'),
		register_agent_identity: f('agents', 'confirm_spend', 'preview_agent_identity', ['asset', 'name', 'network']),
		get_onchain_agent: r('agents'),
		agent_wallet: r('wallet'),
		build_registration: r('agents'),
		list_onchain_agents: r('agents'),
		three_status: r('agents'),
	},
	'naming-mcp': {
		sns_resolve: r('utility'),
		sns_reverse: r('utility'),
		threews_availability: r('utility'),
	},
	'notifications-mcp': {
		delete_notification: f('account', 'confirm_delete', 'list_notifications'),
		get_preferences: r('account'),
		list_notifications: r('account'),
		mark_read: w('account'),
		register_push_device: w('account'),
		set_preferences: w('account'),
		unregister_push_device: f('account', 'confirm_delete', 'get_preferences'),
	},
	'portfolio-mcp': {
		get_portfolio_asset: r('wallet'),
		get_portfolio_history: r('wallet'),
		get_portfolio_summary: r('wallet'),
		get_trades_feed: r('intelligence'),
		get_wallet_balances: r('wallet'),
		preview_transfer: r('wallet'),
		send_transfer: f('wallet', 'confirm_transfer', 'preview_transfer', ['recipient', 'amount', 'mint']),
	},
	'provenance-mcp': {
		append_agent_action: w('agents'),
		list_agent_actions: r('agents'),
		query_action: r('agents'),
	},
	'pumpfun-mcp': {
		...PUMP_MARKET,
		pumpfun_token_3d: r('assets'),
	},
	'scene-mcp': {
		build_world: w('assets'),
		compose_scene: w('assets'),
		export_scene: w('assets'),
		get_scene: r('assets'),
		list_scenes: r('assets'),
	},
	'signals-mcp': {
		get_mirror_leaderboard: r('trading'),
		get_subscriptions: r('trading'),
		list_signal_feeds: r('trading'),
		set_subscription_status: w('trading'),
		subscribe_signal: f('trading', 'confirm_spend', 'list_signal_feeds'),
	},
	'solana-memo-media-mcp': {
		decode_solana_memo_data_uri: r('utility'),
		extract_solana_memo_media: r('utility'),
		find_solana_memo_media: r('utility'),
		get_solana_memo_media_status: r('utility'),
	},
	'three-token-mcp': {
		three_balance: r('wallet'),
		three_price: r('wallet'),
		three_burn: f('wallet', 'confirm_spend', 'three_price', ['usd']),
	},
	'threews-avatar-mcp': {
		avatar: r('assets'),
		avatar_embed_code: r('integrations'),
		get_avatar: r('assets'),
		render_avatar: r('assets'),
	},
	'tutor-mcp': {
		close_session: w('chat'),
		load_session: r('chat'),
	},
	'vanity-mcp': {
		vanity_appraise: r('marketplace'),
		vanity_board: r('marketplace'),
		vanity_config: r('marketplace'),
		vanity_gallery: r('marketplace'),
		vanity_leaderboard: r('marketplace'),
		vanity_open: r('marketplace'),
		vanity_quote: r('marketplace'),
		vanity_stats: r('marketplace'),
	},
	'vision-mcp': {
		analyze_image: r('utility'),
		describe_image: r('utility'),
		get_vision_status: r('utility'),
	},
	'x402-mcp': {
		x402_wallet: r('wallet'),
		find_services: r('x402'),
		inspect_endpoint: r('x402'),
		pay_and_call: f('x402', 'confirm_payment', 'inspect_endpoint', ['url', 'method']),
	},
};

/** Human names for each server id, for the skill document and the settings page. */
export const SERVERS = {
	'three.ws': { title: 'three.ws', endpoint: '/api/mcp', transport: 'remote' },
	'threews-agent': { title: 'Agent Wallet', endpoint: '/api/mcp-agent', transport: 'remote' },
	'threews-3d-studio': { title: '3D Studio', endpoint: '/api/mcp-3d', transport: 'remote' },
	'threews-3d-studio-free': { title: '3D Studio (free)', endpoint: '/api/mcp-studio', transport: 'remote' },
	'threews-x402-bazaar': { title: 'x402 Bazaar', endpoint: '/api/mcp-bazaar', transport: 'remote' },
	'ibm-x402-mcp-remote': { title: 'IBM Granite', endpoint: '/api/ibm-mcp', transport: 'remote' },
	'threews-pumpfun': { title: 'pump.fun data', endpoint: '/api/pump-fun-mcp', transport: 'remote' },
	...Object.fromEntries(
		Object.keys(POLICY)
			.filter((id) => id.endsWith('-mcp'))
			.map((id) => [id, { title: `@three-ws/${id}`, endpoint: `npx -y @three-ws/${id}`, transport: 'stdio' }]),
	),
};
