// @ts-check
// GET /api/cron/changelog-push - automatic changelog delivery to the community
// Telegram channel.
//
// Runs every 20 minutes. Reads the changelog feed baked into the running
// image (public/changelog.json, regenerated by every deploy build), diffs it
// against DB state, and posts anything new to the community Telegram channel.
// Because the feed ships inside the image, entries go out shortly after the
// deploy that made them live, with no manual `npm run changelog:push` step.
//
// X.com delivery is retired (owner directive 2026-07-18): @trythreews posts
// come from the reviewed X content queue (api/cron/x-content.js), not from
// every release. The X lane in api/_lib/changelog-push.js stays but is unused.
// Telegram is the only automatic changelog channel; the on-site changelog,
// RSS feed, and GitHub CHANGELOG.md carry the rest.
//
// A lane whose credentials are absent reports { skipped: 'not_configured' }.
//   Telegram: TELEGRAM_BOT_TOKEN + TELEGRAM_CHANGELOG_CHAT_ID
//
// A failing lane answers 502, which wrapCron records as a failed heartbeat, so
// a stalled lane turns red on /api/ops/health instead of passing silently.
//
// A DB lock (app_settings) keeps overlapping ticks from double-posting.
// Selection, pacing, caps, and message formats live in
// api/_lib/changelog-push.js; the manual scripts in scripts/changelog-*.mjs
// remain for previews (--dry-run) and backfills only.

import { error, json, method, wrapCron } from '../_lib/http.js';
import { acquireLock, releaseLock, loadFeed, pushTelegramLane } from '../_lib/changelog-push.js';
import { requireCron } from '../_lib/cron-auth.js';

export default wrapCron(async (req, res) => {
	if (!method(req, res, ['GET'])) return;
	if (!requireCron(req, res)) return;

	if (!(await acquireLock())) {
		json(res, 200, { ok: true, skipped: 'locked' });
		return;
	}

	let feed;
	try {
		feed = loadFeed();
	} catch (err) {
		await releaseLock().catch(() => {});
		error(res, 500, 'feed_unreadable', String(err?.message || err));
		return;
	}

	try {
		// A throw (DB outage mid-lane) is reported like any other lane error.
		const telegram = await pushTelegramLane(feed).catch((err) => ({ error: String(err?.message || err) }));
		const failed = Boolean(telegram.error);
		if (failed) console.warn('[cron] changelog-push lane error', { telegram });
		json(res, failed ? 502 : 200, { ok: !failed, telegram, x: { skipped: 'retired' } });
	} finally {
		await releaseLock().catch(() => {});
	}
});
