// @ts-check
// GET /api/cron/changelog-push - automatic changelog delivery to the community
// Telegram channel and the @trythreews X thread.
//
// Runs every 20 minutes. Reads the changelog feed baked into the running
// image (public/changelog.json, regenerated by every deploy build), diffs it
// against DB state, and posts anything new to the community Telegram channel.
// Because the feed ships inside the image, entries go out shortly after the
// deploy that made them live, with no manual `npm run changelog:push` step.
//
// X.com delivery was retired on 2026-07-18 and turned back on by the owner on
// 2026-09-24. X posts are capped well under the account's write budget and
// back off on a 429 until X's own reset time, so it is a showcase of the
// newest releases, not the full log; the on-site changelog and RSS carry that.
//
// A lane whose credentials are absent reports { skipped: 'not_configured' }.
//   Telegram: TELEGRAM_BOT_TOKEN + TELEGRAM_CHANGELOG_CHAT_ID
//   X:        X_API_KEY + X_API_SECRET + X_ACCESS_TOKEN + X_ACCESS_SECRET
//
// The lanes are independent: one failing never stops the other from posting.
// Either failing answers 502, which wrapCron records as a failed heartbeat, so
// a stalled lane turns red on /api/ops/health instead of passing silently.
//
// A DB lock (app_settings) keeps overlapping ticks from double-posting.
// Selection, pacing, caps, and message formats live in
// api/_lib/changelog-push.js; the manual scripts in scripts/changelog-*.mjs
// remain for previews (--dry-run) and backfills only.

import { error, json, method, wrapCron } from '../_lib/http.js';
import { acquireLock, releaseLock, loadFeed, pushTelegramLane, pushXLane } from '../_lib/changelog-push.js';
import { requireCron } from '../_lib/cron-auth.js';

export default wrapCron(async (req, res) => {
	if (!method(req, res, ['GET'])) return;
	if (!requireCron(req, res)) return;

	if (!(await acquireLock())) {
		json(res, 200, { ok: true, skipped: 'locked' });
		return;
	}

	let feed;
	try {
		feed = loadFeed();
	} catch (err) {
		await releaseLock().catch(() => {});
		error(res, 500, 'feed_unreadable', String(err?.message || err));
		return;
	}

	// A throw (DB outage mid-lane, an unexpected library fault) is contained to
	// its own lane and reported like any other lane error.
	const runLane = (lane) => lane(feed).catch((err) => ({ error: String(err?.message || err) }));
	try {
		const telegram = await runLane(pushTelegramLane);
		const x = await runLane(pushXLane);
		const failed = Boolean(telegram.error || x.error);
		if (failed) console.warn('[cron] changelog-push lane error', { telegram, x });
		json(res, failed ? 502 : 200, { ok: !failed, telegram, x });
	} finally {
		await releaseLock().catch(() => {});
	}
});
