// The desktop's app registry. Every windowed app is a real three.ws surface
// served from the same origin and framed in a window; the two native apps
// (Settings, Welcome) are rendered by the shell itself. The long tail of
// destinations comes from public/nav-data.js at runtime (see catalog() in
// shell.js), so the launcher can never drift from the site's own navigation.

export const APPS = [
	{
		id: 'create',
		title: 'Create',
		href: '/create',
		hue: 262,
		icon: 'sparkle',
		size: { w: 1040, h: 700 },
		dock: true,
		desktop: true,
		desc: 'Make an agent, avatar, 3D model or token world',
		keywords: ['agent', 'avatar', 'new', 'build', 'selfie'],
	},
	{
		id: 'forge',
		title: 'Forge',
		href: '/forge',
		hue: 24,
		icon: 'cube',
		size: { w: 1080, h: 720 },
		dock: true,
		desktop: true,
		desc: 'Type a prompt, get a textured 3D model',
		keywords: ['text to 3d', 'model', 'glb', 'generate', 'mesh'],
	},
	{
		id: 'discover',
		title: 'Discover',
		href: '/discover',
		hue: 200,
		icon: 'compass',
		size: { w: 1100, h: 720 },
		dock: true,
		desktop: true,
		desc: 'Browse every registered agent on Solana and EVM',
		keywords: ['agents', 'directory', 'search', 'explore'],
	},
	{
		id: 'chat',
		title: 'Chat',
		href: '/chat',
		hue: 152,
		icon: 'chat',
		size: { w: 920, h: 700 },
		dock: true,
		desktop: true,
		desc: 'Talk to an agent',
		keywords: ['assistant', 'talk', 'ai', 'conversation'],
	},
	{
		id: 'marketplace',
		title: 'Marketplace',
		href: '/marketplace',
		hue: 44,
		icon: 'store',
		size: { w: 1100, h: 720 },
		dock: true,
		desktop: true,
		desc: 'Buy and sell agent skills',
		keywords: ['skills', 'buy', 'sell', 'x402', 'store'],
	},
	{
		id: 'studio',
		title: 'Agent Studio',
		href: '/agent-studio',
		hue: 292,
		icon: 'brain',
		size: { w: 1120, h: 740 },
		dock: true,
		desktop: true,
		desc: 'Author brains, skills and personality',
		keywords: ['persona', 'prompt', 'skills', 'author'],
	},
	{
		id: 'mine',
		title: 'My Creations',
		href: '/mine',
		hue: 330,
		icon: 'folder',
		size: { w: 980, h: 660 },
		dock: false,
		desktop: true,
		desc: 'Everything you have made, newest first',
		keywords: ['files', 'library', 'models', 'avatars'],
	},
	{
		id: 'gallery',
		title: 'Gallery',
		href: '/gallery',
		hue: 180,
		icon: 'image',
		size: { w: 1000, h: 680 },
		dock: false,
		desktop: true,
		desc: 'Every public 3D avatar',
		keywords: ['avatars', 'browse'],
	},
	{
		id: 'pulse',
		title: 'Pulse',
		href: '/pulse',
		hue: 340,
		icon: 'pulse',
		size: { w: 1000, h: 680 },
		dock: false,
		desktop: true,
		desc: 'Live feed of agent wallet activity',
		keywords: ['feed', 'wallet', 'activity', 'live', 'money'],
	},
	{
		id: 'trenches',
		title: 'Trenches',
		href: '/trenches',
		hue: 128,
		icon: 'radar',
		size: { w: 1120, h: 740 },
		dock: false,
		desktop: true,
		desc: 'Live Solana launches, runners and smart money',
		keywords: ['solana', 'pump', 'launches', 'tokens', 'wallets'],
	},
	{
		id: 'console',
		title: 'Console',
		href: '/dashboard',
		hue: 220,
		icon: 'terminal',
		size: { w: 1120, h: 740 },
		dock: true,
		desktop: true,
		desc: 'Your agents, wallets and usage',
		keywords: ['dashboard', 'account', 'keys', 'billing'],
	},
	{
		id: 'tour',
		title: 'Tour',
		href: '/tour',
		hue: 100,
		icon: 'play',
		size: { w: 960, h: 660 },
		dock: false,
		desktop: true,
		desc: 'A guided walk through the platform',
		keywords: ['help', 'learn', 'guide', 'tutorial'],
	},
];

export const NATIVE_APPS = [
	{
		id: 'settings',
		title: 'Settings',
		hue: 215,
		icon: 'gear',
		size: { w: 560, h: 560 },
		native: true,
		dock: true,
		desktop: true,
		desc: 'Your profile, personalization, and saved session',
		keywords: ['wallpaper', 'theme', 'preferences', 'classic', 'reset', 'profile', 'accent', 'export', 'storage', 'name'],
	},
	{
		id: 'apps',
		title: 'All Apps',
		hue: 200,
		icon: 'grid',
		size: { w: 720, h: 600 },
		native: true,
		dock: false,
		desktop: true,
		desc: 'Every three.ws app and page, with shortcuts for your desktop',
		keywords: ['files', 'explorer', 'pin', 'shortcut', 'launcher', 'catalog'],
	},
	{
		id: 'welcome',
		title: 'Welcome',
		hue: 262,
		icon: 'logo',
		size: { w: 640, h: 520 },
		native: true,
		dock: false,
		desktop: false,
		desc: 'What three.ws is and where to start',
		keywords: ['about', 'intro', 'start'],
	},
];

export const ALL_APPS = [...APPS, ...NATIVE_APPS];

export function appById(id) {
	return ALL_APPS.find((a) => a.id === id) || null;
}

export const WALLPAPERS = [
	{ id: 'aurora', label: 'Aurora' },
	{ id: 'midnight', label: 'Midnight' },
	{ id: 'solana', label: 'Solana' },
	{ id: 'ember', label: 'Ember' },
	{ id: 'graphite', label: 'Graphite' },
];
export const CUSTOM_WALL = 'custom';
