export type AirdropStatus = 'upcoming' | 'claimable' | 'ended' | 'rumored';

export interface AirdropEntry {
  id: string;
  protocol: string;
  token: string;
  symbol: string;
  chain: string;
  status: AirdropStatus;
  description: string;
  claimUrl?: string;
  snapshotDate?: string;
  claimDeadline?: string;
  launchDate?: string;
  estimatedValue?: string;
  eligibility: string[];
  tasks?: string[];
  confirmed: boolean;
  category: 'DeFi' | 'L1' | 'L2' | 'NFT' | 'Infrastructure' | 'Social';
  links: {
    website?: string;
    twitter?: string;
    announcement?: string;
    checker?: string;
  };
}

/**
 * Curated airdrop registry - updated manually.
 * Status meanings:
 *  - rumored: no official token announcement; speculation based on points programs / fundraises
 *  - upcoming: officially confirmed but not yet claimable
 *  - claimable: live claim window open
 *  - ended: claim window closed or fully distributed
 *
 * DISCLAIMER: Estimated values are speculative and not financial advice.
 */
export const AIRDROP_REGISTRY: AirdropEntry[] = [
  // ─── Claimable ───────────────────────────────────────────
  {
    id: 'starknet-provisions',
    protocol: 'Starknet',
    token: 'STRK',
    symbol: 'STRK',
    chain: 'Starknet',
    status: 'claimable',
    description: 'Starknet Provisions - second wave of STRK token distribution for early users and developers',
    claimUrl: 'https://provisions.starknet.io',
    claimDeadline: '2026-06-15',
    estimatedValue: '~$100-$2,000 depending on activity',
    eligibility: ['Early Starknet bridge user', 'Deployed contracts on Starknet', 'Active DeFi user on Starknet'],
    confirmed: true,
    category: 'L2',
    links: {
      website: 'https://starknet.io',
      twitter: 'https://twitter.com/Starknet',
      checker: 'https://provisions.starknet.io',
    },
  },
  {
    id: 'eigenlayer-season2',
    protocol: 'EigenLayer',
    token: 'EIGEN',
    symbol: 'EIGEN',
    chain: 'Ethereum',
    status: 'claimable',
    description: 'EigenLayer Season 2 stakedrop for restakers and operators',
    claimUrl: 'https://claims.eigenfoundation.org',
    claimDeadline: '2026-05-01',
    estimatedValue: '~$200-$5,000 for restakers',
    eligibility: ['Restaked ETH on EigenLayer', 'Ran an EigenLayer operator', 'Held liquid restaking tokens'],
    confirmed: true,
    category: 'Infrastructure',
    links: {
      website: 'https://eigenlayer.xyz',
      twitter: 'https://twitter.com/eigenlayer',
      checker: 'https://claims.eigenfoundation.org',
    },
  },

  // ─── Upcoming (confirmed) ────────────────────────────────
  {
    id: 'zksync-season2',
    protocol: 'zkSync',
    token: 'ZK',
    symbol: 'ZK',
    chain: 'zkSync Era',
    status: 'upcoming',
    description: 'zkSync Season 2 token distribution for continued ecosystem users',
    launchDate: '2026-Q2',
    estimatedValue: '~$100-$3,000 depending on activity',
    eligibility: ['Used zkSync Era after Season 1 snapshot', 'Provided liquidity on zkSync DEXs', 'Participated in zkSync governance'],
    tasks: ['Bridge to zkSync Era', 'Use 3+ dApps', 'Maintain consistent activity'],
    confirmed: true,
    category: 'L2',
    links: {
      website: 'https://zksync.io',
      twitter: 'https://twitter.com/zaboris',
    },
  },
  {
    id: 'layerzero-season2',
    protocol: 'LayerZero',
    token: 'ZRO',
    symbol: 'ZRO',
    chain: 'Multi-chain',
    status: 'upcoming',
    description: 'LayerZero Season 2 distribution for cross-chain messaging users',
    launchDate: '2026-Q2',
    estimatedValue: '~$50-$1,500',
    eligibility: ['Sent cross-chain messages via LayerZero', 'Used Stargate Finance', 'Bridged across 3+ chains'],
    tasks: ['Use LayerZero-powered bridges', 'Message across multiple chains'],
    confirmed: true,
    category: 'Infrastructure',
    links: {
      website: 'https://layerzero.network',
      twitter: 'https://twitter.com/LayerZero_Labs',
    },
  },
  {
    id: 'hyperlane-token',
    protocol: 'Hyperlane',
    token: 'HYP',
    symbol: 'HYP',
    chain: 'Multi-chain',
    status: 'upcoming',
    description: 'Hyperlane interoperability protocol token launch for early relayers and users',
    launchDate: '2026-Q1',
    estimatedValue: '~$200-$2,000',
    eligibility: ['Ran a Hyperlane relayer', 'Used Hyperlane messaging', 'Deployed Hyperlane contracts'],
    confirmed: true,
    category: 'Infrastructure',
    links: {
      website: 'https://hyperlane.xyz',
      twitter: 'https://twitter.com/Hyperlane_xyz',
    },
  },

  // ─── Rumored ─────────────────────────────────────────────
  {
    id: 'linea-mainnet',
    protocol: 'Linea',
    token: 'LINEA',
    symbol: 'LINEA',
    chain: 'Linea',
    status: 'rumored',
    description: 'Linea mainnet token distribution for early bridge & DeFi users',
    estimatedValue: '~$500-$3,000 for active users',
    eligibility: ['Bridge to Linea', 'Use Linea DeFi protocols', 'Hold LXP points'],
    tasks: ['Bridge ETH via official bridge', 'Use 3+ DeFi protocols on Linea', 'Participate in Linea Surge'],
    confirmed: false,
    category: 'L2',
    links: {
      website: 'https://linea.build',
      twitter: 'https://twitter.com/LineaBuild',
    },
  },
  {
    id: 'scroll-token',
    protocol: 'Scroll',
    token: 'SCR',
    symbol: 'SCR',
    chain: 'Scroll',
    status: 'rumored',
    description: 'Scroll zkEVM potential token distribution for Scroll Marks holders',
    estimatedValue: '~$200-$2,500',
    eligibility: ['Bridge to Scroll', 'Use DeFi on Scroll', 'Accumulate Scroll Marks / Session points'],
    tasks: ['Bridge assets to Scroll', 'Provide liquidity on Scroll DEXs', 'Use lending protocols'],
    confirmed: false,
    category: 'L2',
    links: {
      website: 'https://scroll.io',
      twitter: 'https://twitter.com/Scroll_ZKP',
    },
  },
  {
    id: 'metamask-token',
    protocol: 'MetaMask',
    token: 'MASK',
    symbol: 'MASK',
    chain: 'Ethereum',
    status: 'rumored',
    description: 'MetaMask wallet token - long-rumored for active wallet users',
    estimatedValue: '~$500-$5,000 (highly speculative)',
    eligibility: ['Active MetaMask user', 'Used MetaMask Swaps', 'Used MetaMask Bridge'],
    tasks: ['Use the MetaMask swap aggregator', 'Bridge via MetaMask Bridge', 'Maintain regular activity'],
    confirmed: false,
    category: 'Infrastructure',
    links: {
      website: 'https://metamask.io',
      twitter: 'https://twitter.com/MetaMask',
    },
  },
  {
    id: 'phantom-token',
    protocol: 'Phantom',
    token: 'PHANTOM',
    symbol: 'PHANTOM',
    chain: 'Solana',
    status: 'rumored',
    description: 'Phantom wallet potential token for power users of multi-chain wallet',
    estimatedValue: '~$200-$3,000 (speculative)',
    eligibility: ['Active Phantom user', 'Used Phantom swaps', 'Multi-chain Phantom user'],
    tasks: ['Use Phantom on Solana, Ethereum, Polygon', 'Swap via in-wallet aggregator'],
    confirmed: false,
    category: 'Infrastructure',
    links: {
      website: 'https://phantom.app',
      twitter: 'https://twitter.com/phantom',
    },
  },
  {
    id: 'berachain-token',
    protocol: 'Berachain',
    token: 'BERA',
    symbol: 'BERA',
    chain: 'Berachain',
    status: 'rumored',
    description: 'Berachain PoL (Proof of Liquidity) L1 token for testnet & early DeFi users',
    estimatedValue: '~$500-$5,000',
    eligibility: ['Used Berachain testnet', 'Provided liquidity in Berachain DeFi', 'Held Bong Bears NFTs'],
    tasks: ['Participate in Berachain testnet', 'Provide liquidity on BEX', 'Use Bend lending'],
    confirmed: false,
    category: 'L1',
    links: {
      website: 'https://berachain.com',
      twitter: 'https://twitter.com/beaboris',
    },
  },
  {
    id: 'grass-season2',
    protocol: 'Grass',
    token: 'GRASS',
    symbol: 'GRASS',
    chain: 'Solana',
    status: 'rumored',
    description: 'Grass Season 2 airdrop for bandwidth contributors',
    estimatedValue: '~$50-$500',
    eligibility: ['Running Grass node', 'Contributed bandwidth during Season 2'],
    tasks: ['Install Grass browser extension', 'Keep node running consistently'],
    confirmed: false,
    category: 'Infrastructure',
    links: {
      website: 'https://grassfoundation.io',
      twitter: 'https://twitter.com/getgrass_io',
    },
  },
  {
    id: 'monad-token',
    protocol: 'Monad',
    token: 'MON',
    symbol: 'MON',
    chain: 'Monad',
    status: 'rumored',
    description: 'Monad high-performance L1 token for testnet participants',
    estimatedValue: '~$500-$5,000 (speculative)',
    eligibility: ['Monad testnet user', 'Active community member', 'Discord OG role'],
    tasks: ['Join Monad testnet when available', 'Engage in community activities'],
    confirmed: false,
    category: 'L1',
    links: {
      website: 'https://monad.xyz',
      twitter: 'https://twitter.com/moaboris',
    },
  },
  {
    id: 'fuel-token',
    protocol: 'Fuel',
    token: 'FUEL',
    symbol: 'FUEL',
    chain: 'Fuel',
    status: 'rumored',
    description: 'Fuel modular execution layer token for early network users',
    estimatedValue: '~$200-$2,000',
    eligibility: ['Used Fuel testnet', 'Built on Fuel (Sway)', 'Participated in Fuel points program'],
    tasks: ['Deploy contracts on Fuel testnet', 'Bridge assets to Fuel', 'Use Fuel-native dApps'],
    confirmed: false,
    category: 'L1',
    links: {
      website: 'https://fuel.network',
      twitter: 'https://twitter.com/fuel_network',
    },
  },
  {
    id: 'eclipse-token',
    protocol: 'Eclipse',
    token: 'ECLIPSE',
    symbol: 'ECLIPSE',
    chain: 'Eclipse',
    status: 'rumored',
    description: 'Eclipse SVM L2 on Ethereum - token for early DeFi and bridge users',
    estimatedValue: '~$200-$3,000',
    eligibility: ['Bridged to Eclipse', 'Used Eclipse DeFi', 'Participated in testnet'],
    tasks: ['Bridge ETH to Eclipse', 'Trade on Eclipse DEXs', 'Provide liquidity'],
    confirmed: false,
    category: 'L2',
    links: {
      website: 'https://eclipse.xyz',
      twitter: 'https://twitter.com/EclipseFND',
    },
  },
  {
    id: 'initia-token',
    protocol: 'Initia',
    token: 'INIT',
    symbol: 'INIT',
    chain: 'Initia',
    status: 'rumored',
    description: 'Initia interwoven rollup platform token for early adopters',
    estimatedValue: '~$200-$2,000',
    eligibility: ['Used Initia testnet', 'Participated in Initiation quests', 'Active community member'],
    tasks: ['Complete Initiation quests', 'Bridge to Initia testnet', 'Use Initia Move dApps'],
    confirmed: false,
    category: 'L1',
    links: {
      website: 'https://initia.xyz',
      twitter: 'https://twitter.com/initaboris',
    },
  },
  {
    id: 'abstract-token',
    protocol: 'Abstract',
    token: 'ABS',
    symbol: 'ABS',
    chain: 'Abstract',
    status: 'rumored',
    description: 'Abstract consumer-focused L2 token for early adopters and creators',
    estimatedValue: '~$100-$1,500',
    eligibility: ['Used Abstract chain', 'Created or collected on Abstract', 'Held Pudgy Penguins'],
    tasks: ['Bridge to Abstract', 'Use Abstract dApps', 'Engage with creator ecosystem'],
    confirmed: false,
    category: 'L2',
    links: {
      website: 'https://abs.xyz',
      twitter: 'https://twitter.com/AbstractChain',
    },
  },
  {
    id: 'story-protocol-token',
    protocol: 'Story Protocol',
    token: 'STORY',
    symbol: 'STORY',
    chain: 'Story',
    status: 'rumored',
    description: 'Story Protocol IP blockchain token for early IP registrants',
    estimatedValue: '~$100-$2,000',
    eligibility: ['Registered IP on Story testnet', 'Used Story SDK', 'Community contributor'],
    tasks: ['Register IP assets on Story', 'Build with Story SDK'],
    confirmed: false,
    category: 'L1',
    links: {
      website: 'https://storyprotocol.xyz',
      twitter: 'https://twitter.com/StoryProtocol',
    },
  },
  {
    id: 'zircuit-season2',
    protocol: 'Zircuit',
    token: 'ZRC',
    symbol: 'ZRC',
    chain: 'Zircuit',
    status: 'rumored',
    description: 'Zircuit Season 2 token distribution for restakers and DeFi users',
    estimatedValue: '~$100-$1,000',
    eligibility: ['Staked in Zircuit staking', 'Used Zircuit DeFi', 'Earned Zircuit points'],
    tasks: ['Stake ETH/LSTs on Zircuit', 'Use Zircuit mainnet dApps'],
    confirmed: false,
    category: 'L2',
    links: {
      website: 'https://zircuit.com',
      twitter: 'https://twitter.com/ZircuitL2',
    },
  },
  {
    id: 'symbiotic-token',
    protocol: 'Symbiotic',
    token: 'SYMB',
    symbol: 'SYMB',
    chain: 'Ethereum',
    status: 'rumored',
    description: 'Symbiotic restaking protocol token for early depositors',
    estimatedValue: '~$200-$3,000',
    eligibility: ['Deposited into Symbiotic vaults', 'Earned Symbiotic points', 'Used partner protocols'],
    tasks: ['Deposit wstETH/other collateral into Symbiotic', 'Accumulate points'],
    confirmed: false,
    category: 'DeFi',
    links: {
      website: 'https://symbiotic.fi',
      twitter: 'https://twitter.com/symbioticfi',
    },
  },
  {
    id: 'karak-token',
    protocol: 'Karak',
    token: 'KARAK',
    symbol: 'KARAK',
    chain: 'Multi-chain',
    status: 'rumored',
    description: 'Karak restaking protocol token for early restakers',
    estimatedValue: '~$100-$2,000',
    eligibility: ['Restaked on Karak', 'Earned XP points', 'Used Karak multi-chain vaults'],
    tasks: ['Deposit into Karak vaults', 'Accumulate XP across chains'],
    confirmed: false,
    category: 'DeFi',
    links: {
      website: 'https://karak.network',
      twitter: 'https://twitter.com/Karak_Network',
    },
  },
  {
    id: 'ambient-finance-token',
    protocol: 'Ambient Finance',
    token: 'AMBIENT',
    symbol: 'AMBIENT',
    chain: 'Multi-chain',
    status: 'rumored',
    description: 'Ambient Finance (fka CrocSwap) DEX token for LPs and traders',
    estimatedValue: '~$100-$1,500',
    eligibility: ['Provided liquidity on Ambient', 'Active trader on Ambient', 'Used Ambient on multiple chains'],
    tasks: ['Provide concentrated liquidity', 'Trade on Ambient DEX', 'Use Ambient on Scroll, Blast, etc.'],
    confirmed: false,
    category: 'DeFi',
    links: {
      website: 'https://ambient.finance',
      twitter: 'https://twitter.com/ambient_finance',
    },
  },

  // ─── Recently Ended (for reference) ──────────────────────
  {
    id: 'wormhole-w',
    protocol: 'Wormhole',
    token: 'W',
    symbol: 'W',
    chain: 'Solana',
    status: 'ended',
    description: 'Wormhole cross-chain messaging protocol token distribution',
    estimatedValue: '$200-$2,000 (actual)',
    eligibility: ['Used Wormhole bridges', 'Portal bridge users', 'Cross-chain message senders'],
    confirmed: true,
    category: 'Infrastructure',
    links: {
      website: 'https://wormhole.com',
      twitter: 'https://twitter.com/waboris',
    },
  },
  {
    id: 'ethena-ena',
    protocol: 'Ethena',
    token: 'ENA',
    symbol: 'ENA',
    chain: 'Ethereum',
    status: 'ended',
    description: 'Ethena synthetic dollar protocol - Shard Campaign airdrop',
    estimatedValue: '$500-$10,000+ (actual)',
    eligibility: ['Held USDe', 'Staked sUSDe', 'Earned Ethena Shards'],
    confirmed: true,
    category: 'DeFi',
    links: {
      website: 'https://ethena.fi',
      twitter: 'https://twitter.com/ethena_labs',
    },
  },
  {
    id: 'jupiter-jup-s2',
    protocol: 'Jupiter',
    token: 'JUP',
    symbol: 'JUP',
    chain: 'Solana',
    status: 'ended',
    description: 'Jupiter DEX aggregator Season 2 airdrop (Jupuary)',
    estimatedValue: '$100-$5,000 (actual)',
    eligibility: ['Used Jupiter swap aggregator', 'Held JUP', 'Active Solana DeFi user'],
    confirmed: true,
    category: 'DeFi',
    links: {
      website: 'https://jup.ag',
      twitter: 'https://twitter.com/JupiterExchange',
    },
  },
  {
    id: 'dymension-dym',
    protocol: 'Dymension',
    token: 'DYM',
    symbol: 'DYM',
    chain: 'Dymension',
    status: 'ended',
    description: 'Dymension RollApp ecosystem genesis drop',
    estimatedValue: '$200-$3,000 (actual)',
    eligibility: ['Staked ATOM/TIA/other Cosmos tokens', 'Used Dymension testnet'],
    confirmed: true,
    category: 'L1',
    links: {
      website: 'https://dymension.xyz',
      twitter: 'https://twitter.com/daboris',
    },
  },
  {
    id: 'parcl-prcl',
    protocol: 'Parcl',
    token: 'PRCL',
    symbol: 'PRCL',
    chain: 'Solana',
    status: 'ended',
    description: 'Parcl real estate perps - points program airdrop',
    estimatedValue: '$50-$500 (actual)',
    eligibility: ['Deposited into Parcl vaults', 'Traded Parcl markets', 'Earned Parcl points'],
    confirmed: true,
    category: 'DeFi',
    links: {
      website: 'https://parcl.co',
      twitter: 'https://twitter.com/Parcl',
    },
  },
];
