/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sirsaugsage (https://sketchfab.com/sirsausage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-game-inn-192bf30a7e28425ab385aef19769d4b0
Title: Fantasy Game Inn
*/

import { Clone, Helper, Merged, useGLTF, useHelper } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { useControls } from "leva";
import { useEffect, useRef } from "react";
import { MeshBVHHelper } from "three-mesh-bvh";

export default function Map(props) {
  /**
   * Initialize
   */
  const mapMeshRef = useRef(null);
  // Load map model
  const bakeInnModel = useGLTF("./fantasy_game_inn.glb");
  const su7Model = useGLTF("./SU7.glb");

  // useEffect(()=>{
  // console.log(mapMeshRef.current.geometry.boundsTree);
  // nodes.TheInn_bakeInn_0.geometry.deleteAttribute('uv1');
  // },[])

  // useHelper(mapMeshRef, MeshBVHHelper, 20)

  // let time = 0
  // useFrame((_, delta)=>{
  //   time+=delta
  //   if(mapMeshRef.current) {
  //     mapMeshRef.current.position.z = Math.sin(time)
  //     mapMeshRef.current.geometry.boundsTree.refit()
  //   }
  // })

  return (
    <group {...props} dispose={null}>
      {/* <Clone object={bakeInnModel.scene} position={[-33, -8, -2]} /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={bakeInnModel.nodes.TheInn_bakeInn_0.geometry}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.11}
      >
        <meshStandardMaterial map={bakeInnModel.materials.bakeInn.map} />
      </mesh>
      {/* <Clone object={su7Model.scene} position={[0, -1.2, 4.5]} /> */}
    </group>
  );
}

useGLTF.preload("./fantasy_game_inn.glb");
// useGLTF.preload("./SU7.glb");
