// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

/// @title FixedSupplyToken
/// @notice The EVM launch venue for three.ws agents: a plain OpenZeppelin ERC-20
///         whose entire supply is minted once, in the constructor, to the
///         launching agent's wallet. There is no owner, no mint function, no
///         pause, no blacklist and no upgrade path, so the supply the launch
///         page shows is the supply that exists forever.
/// @dev    Deployed by api/_lib/evm-leg/launch.js from the agent's custodial EVM
///         key. The compiled artifact lives at api/_lib/evm-leg/fixed-supply-token.json
///         and is regenerated by scripts/build-fixed-supply-token.mjs.
contract FixedSupplyToken is ERC20 {
    /// @param name_      Token name.
    /// @param symbol_    Token symbol.
    /// @param supply_    Whole-token supply (18 decimals are applied here).
    /// @param recipient_ Receives the entire supply at deploy time.
    constructor(string memory name_, string memory symbol_, uint256 supply_, address recipient_)
        ERC20(name_, symbol_)
    {
        require(recipient_ != address(0), "recipient is zero");
        require(supply_ > 0, "supply is zero");
        _mint(recipient_, supply_ * 10 ** decimals());
    }
}
